version: "3.1"

services:
  web:
    build:
      context: .
    ports:
      - '8090:5000'
    depends_on:
      - db
    secrets:
      - db-password

  db:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password

secrets:
  db-password:
    file: ./db-password.txt


